/* Generated by Nim Compiler v1.0.6 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q;
typedef struct tyObject_JavaVMInitArgs__cKymzNrkoBnuXJDMMaEfiA tyObject_JavaVMInitArgs__cKymzNrkoBnuXJDMMaEfiA;
typedef N_CDECL_PTR(NI32, tyProc__VeWZhCOugPV742UOEm7dbg) (tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q*** pvm, void** penv, void* args);
typedef N_CDECL_PTR(NI32, tyProc__I3c9az5111PCFEMM1gYcH1A) (tyObject_JavaVMInitArgs__cKymzNrkoBnuXJDMMaEfiA* vm_args);
typedef N_CDECL_PTR(NI32, tyProc__YrUoJ6tyx2AIkIhA9celD0Q) (tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q*** vmBuf, NI32 bufLen, NI32* nVMs);
tyProc__VeWZhCOugPV742UOEm7dbg JNI_CreateJavaVM__JtrSv0NNKo8S2XKSj5JUEA;
tyProc__I3c9az5111PCFEMM1gYcH1A JNI_GetDefaultJavaVMInitArgs__vGe5z1qA6HlNq0gvaRLF8w;
tyProc__YrUoJ6tyx2AIkIhA9celD0Q JNI_GetCreatedJavaVMs__p1eaEgr9cGNRGolefCPJoNw;
