/* Generated by Nim Compiler v1.0.6 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q;
typedef struct tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg;
typedef struct tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw;
typedef struct tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q;
typedef struct tyObject_jthrowablecolonObjectType___evWc9b49biOgNwOnXGhS2vGA tyObject_jthrowablecolonObjectType___evWc9b49biOgNwOnXGhS2vGA;
typedef union tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg;
typedef struct tyObject_jarraycolonObjectType___RmEW8whL9cBQ8DcJ70FJ6lg tyObject_jarraycolonObjectType___RmEW8whL9cBQ8DcJ70FJ6lg;
typedef struct tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw;
typedef struct tyObject_JNINativeMethod__L6bdxAULUoPq6MmpjHdhEA tyObject_JNINativeMethod__L6bdxAULUoPq6MmpjHdhEA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ {
char dummy;
};
struct tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg {
  tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ Sup;
};
typedef N_CDECL_PTR(NI32, tyProc__GTiyzoLqRtZelJ9cswu7Uow) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env);
typedef N_CDECL_PTR(tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q*, tyProc__DFZxGxC0ZHf9bsKfZXJiERg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NCSTRING name, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* loader, NI8* buf, NI32 len);
typedef N_CDECL_PTR(tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q*, tyProc__em7j1GBs7VNAXMH7F9bsLzA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NCSTRING name);
typedef N_CDECL_PTR(void*, tyProc__RI5QcbnF5rKJCpfe5tSkuw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* meth);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__6GaozS8Gb3Dr0wKgiJkjkQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* cls, void* methodID, NU8 isStatic);
typedef N_CDECL_PTR(tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q*, tyProc__VWJPYSlzvPXlCZ6l3afNaA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* sub);
typedef N_CDECL_PTR(NU8, tyProc__4CPVQiZTL1EgQ5WgxnZgfQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* sub, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* sup);
typedef N_CDECL_PTR(NI32, tyProc__iJRdrCdAU19cu9cNbozr6Lww) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jthrowablecolonObjectType___evWc9b49biOgNwOnXGhS2vGA* obj);
typedef N_CDECL_PTR(NI32, tyProc__8haEwIKzLtY9ahp2OaQCKPA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, NCSTRING msg);
typedef N_CDECL_PTR(tyObject_jthrowablecolonObjectType___evWc9b49biOgNwOnXGhS2vGA*, tyProc__PA9cdiVOg516By6pGvaQWxw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env);
typedef N_CDECL_PTR(void, tyProc__TFdHnXCI9aRT5twkNf9boeCQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env);
typedef N_CDECL_PTR(void, tyProc__zprQk8MzhuZuCVVfs7nzAQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NCSTRING msg);
typedef N_CDECL_PTR(NI32, tyProc__bHzJcWtjDNDl5kZqzPrAZA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NI32 capacity);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__9aa48FNC3q6O6o7JxBTqyIg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* res);
typedef N_CDECL_PTR(void, tyProc__g66UlTcFcTsHnYKbhCcgkQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj);
typedef N_CDECL_PTR(NU8, tyProc__bOP4TXpDkCCdPUdwBShcHg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj1, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj2);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__JzQGCKUL8PcNxxx7x5sbnQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__xDGZyxEkNgFs49a0XpRnqkw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__etz1nMATyY52waZ3IHPvNA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q*, tyProc__7siyna4EZ2o31AWmBTAyeQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj);
typedef N_CDECL_PTR(NU8, tyProc__Gpd9aw5aWm5w1vetb49cc9cbA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz);
typedef N_CDECL_PTR(void*, tyProc__SJltzEg0qYejYe9c9cKJtVhg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, NCSTRING name, NCSTRING sig);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__URa83EjSMygGDUgxAj7NJA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__73B0l7AF0UoF9c4pPSoPTtQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NU8, tyProc__BzA25CAZLkmSibqrGJQJRw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(NU8, tyProc__h0HQthcF0bCGXZqy9cjpTqw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI8, tyProc__dg2OkZ2plylt11Mvu1y1rg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(NI8, tyProc__t9b0wgXJxuXOxUZ7eVy24Lw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NU16, tyProc__sukDG9ctV6DmP4uGvm9bg73Q) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(NU16, tyProc__WTPd4nGpA9bMpOX9cuVNdWng) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI16, tyProc__ysjVE7f0HAax7bq4l7H2sw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(NI16, tyProc__8ZgUh9bmR8aEVUx9bRfh4E4g) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI32, tyProc__RebaplENYTeDvBpbs8enhQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(NI32, tyProc__xkCZtbggsh19c9cU9c4avy0bQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI64, tyProc__7g2iT9ct0rSELGwHNk0j9bmQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(NI64, tyProc__Dm9aqf3hllLiPUfPaYQrmyg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(float, tyProc__y9bhXimZiIQn0z6jBF5f9a9aQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(float, tyProc__Ft9aYwW7WlkAUG1lYfYiwsg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(double, tyProc__xUnV47uHdxyCxToMt3Q8Tw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(double, tyProc__H7q29cexnsDarOisryxp6EA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(void, tyProc__GhcJ30BBWy7mGl1OYwk1TQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(void, tyProc__IoTRuk1FmbmpFwkYmwOOLg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__7Nyg9b26IwfN3eF9asvxJyjQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__19aFJrxpFMbyj7qtk9bz4aug) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NU8, tyProc__J9bY9cgAnW8ccgmsFx3gMZug) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NU8, tyProc__OFtxxZM5F3VNTX54GJ6i4A) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI8, tyProc__y3Vi5W4aX0z9aZ4iDZX79cWA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI8, tyProc__TYQ6u1SyWHsM16Sf58qYjQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NU16, tyProc__OpBC6GpFv76W9a13eeRvAxg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NU16, tyProc__tDXD2y1NzOhFLd2AtDZ5fw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI16, tyProc__2sD9a8bY2lRkreVu9ch5NsbQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI16, tyProc__kLRxt2NWwWNJtDOvfW7C8A) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI32, tyProc__lvrbik67MMqeZyfUKBbAUw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI32, tyProc__h9b5XpAcA9c8vchySeXxzz9cw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI64, tyProc__f38f9bsO9cRyGpsCgHR1FCZA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI64, tyProc__aYl9aBKJep8aKhMwfadpAHw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(float, tyProc__CwkFdXNtFQmKc2KXYt2ung) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(float, tyProc__1VXPEsYRNNVX5lYxCNRYMw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(double, tyProc__r5RRdhUbOSZE9cwdT8oa2gg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(double, tyProc__CbVHy2WREs7HuHbKZLp3jA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(void, tyProc__Os2Eb35jwxBI2IIaWEc0iw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(void, tyProc__kEP8rOSas4sqUu8zf8xYcA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__HKl3wK9aCr9cr0LME4r9cmLIw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(NU8, tyProc__woDGiIz55pLskIEHDrGMdQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(NI8, tyProc__8rYdJg9cJMxMAQ4MSkIFt1Q) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(NU16, tyProc__QwHLU6Lv1w3ycvSPx9c745w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(NI16, tyProc__jUbiAb82AubqZuyUK5NuZw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(NI32, tyProc__D6FiM33IqK32mlI9aNPEkJg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(NI64, tyProc__gD9cnKXpTgMQH8d5PNQD9cPw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(float, tyProc__SDgCYc9b09axbMEG9baj2AwXg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(double, tyProc__yFoPhk0ty5WF3PixBEnhlg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(void, tyProc__Q79bW7rqWtOdXHvbC0xgwpw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* val);
typedef N_CDECL_PTR(void, tyProc__1MtrO0a1W77R9aGli57hiXA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, NU8 val);
typedef N_CDECL_PTR(void, tyProc__KQ6ildJWMBeSuuUfBSLrWA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, NI8 val);
typedef N_CDECL_PTR(void, tyProc__CMmqxHzWH24SCa9brIS5eRw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, NU16 val);
typedef N_CDECL_PTR(void, tyProc__rL3xq0MYJhI9cYsnvEKDr5w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, NI16 val);
typedef N_CDECL_PTR(void, tyProc__GQnO7229cfacsjZumf0Q9clw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, NI32 val);
typedef N_CDECL_PTR(void, tyProc__17Efc9ajSb8uo1XtdJADKBA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, NI64 val);
typedef N_CDECL_PTR(void, tyProc__PcK9a3D3iUIwc9bEYJ8ZuIsw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, float val);
typedef N_CDECL_PTR(void, tyProc__lqb0t9cEiwEAHi8L38RRSeg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, double val);
typedef N_CDECL_PTR(NU8, tyProc__oD1wB8LRTaHI59b6cGvpO0w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NU8, tyProc__X8lAGCfdjCkE2G4IRgr9c4Q) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI8, tyProc__aShA4zRKZgt4bb2XM4Qcsg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI8, tyProc__HwTntITjqWFDX7udUDz03w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NU16, tyProc__iKhWl09a2L9axud17FyRc79ag) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NU16, tyProc__OEUP0541MEkD08qEqW3tBw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI16, tyProc__hYNeRrdEzkJngiBnJEiWKQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI16, tyProc__eimIiGQ89bNtCAVEcDJsvjw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI32, tyProc__ZgsI9cTHCZU9b9cuyfkloXi7w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI32, tyProc__pYQBnp2d7pPp7xQK9bsvhzw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI64, tyProc__kciRoaFdhzsFCxtNOZGWQA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI64, tyProc__qO1ANjb6RyH1C7D0AR9avVg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(float, tyProc__S4qMlh9bL1ZpfswLRA9cplMQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(float, tyProc__MP9cpv9bGHOwYgo2sxF8B9a1w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(double, tyProc__AOdcvx2hpu8FHwMz7ncFZw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(double, tyProc__IiickGRlm8vONDL50qqdTw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(void, tyProc__cWBN380E5Fl8ojwbB9bc9a3w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(void, tyProc__sHkF9c3NXDPxCbGYf8WGRGQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__YBy37W0c9ci9b5Q2DOLx2eaw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(NU8, tyProc__heJ5040WdyFhZw0AEVJUOA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(NI8, tyProc__Qqu9brExW2XMBElI7GiBgEg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(NU16, tyProc__cTBAW5ffLFlwmGSnN2Z7jw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(NI16, tyProc__C7mA6ssTTci9bUPqBlcY2OA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(NI32, tyProc__QiJvubdgP9aIlNSZJp0UsDg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(NI64, tyProc__9a4HemB9a9anUp8UmyV2ji6Pg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(float, tyProc__AN6iNgJutnYqiOS9cfp7Awg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(double, tyProc__28AXZfa9aHIhOKZLaIjLO2Q) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(void, tyProc__mCGxu1EweGI7DCYm8BC0yg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* val);
typedef N_CDECL_PTR(void, tyProc__gD0bgFryRPOZmXVW8x0dTQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, NU8 val);
typedef N_CDECL_PTR(void, tyProc__XeiX37CjfbMPKhLpVU9cbug) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, NI8 val);
typedef N_CDECL_PTR(void, tyProc__imFN1Tums7HoxjCtoL9aSXQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, NU16 val);
typedef N_CDECL_PTR(void, tyProc__CNIFxPt7Kaqp7jkAbnKFWg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, NI16 val);
typedef N_CDECL_PTR(void, tyProc__A1nREStm4FfgwYnHXlEukw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, NI32 val);
typedef N_CDECL_PTR(void, tyProc__AVao9bU8Z9az6o2gWKy9bSJaA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, NI64 val);
typedef N_CDECL_PTR(void, tyProc__h7OHQ8v9cA7PA5IGNw0R8XQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, float val);
typedef N_CDECL_PTR(void, tyProc__M2LrteZhe9cHbQ7aIEP67Dw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, double val);
typedef N_CDECL_PTR(tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg*, tyProc__6A9ckVwXiYF9cc7a6aMcJdsQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NU16* unicode, NI32 len);
typedef N_CDECL_PTR(NI32, tyProc__LF8gX9cmMvFUtPIHtUMTa8w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* str);
typedef N_CDECL_PTR(NU16*, tyProc__QgPmBpFgYnNO1DMkZ9bkAGg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* str, NU8* isCopy);
typedef N_CDECL_PTR(void, tyProc__5XgIEXPkM8d1N9cw3x3iMtA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* str, NU16* chars);
typedef N_CDECL_PTR(tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg*, tyProc__Et9cjhyiZpwit9acXjrn1mUQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NCSTRING s);
typedef N_CDECL_PTR(NCSTRING, tyProc__MCpPI6cWjZouNCHV3dU7CQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* s, NU8* isCopy);
typedef N_CDECL_PTR(void, tyProc__kpocOvZt9a7ioin7z16OCHQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* s, NCSTRING cstr);
typedef N_CDECL_PTR(NI32, tyProc__RgdS2hOQ69cMIL8hjRKXu6w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jarraycolonObjectType___RmEW8whL9cBQ8DcJ70FJ6lg* arr);
typedef N_CDECL_PTR(tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw*, tyProc__nJ4j9cjdJLDxpitP7l9aqHFg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NI32 size, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* init);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__pGxS2vufrSWYIHJmMGj3fQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 index);
typedef N_CDECL_PTR(void, tyProc__JQcWEFa1IdR1ickYsVcIiw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 index, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* val);
typedef N_CDECL_PTR(tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw*, tyProc__9bFoncTBW66OFCLNoWeVSCg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NI32 len);
typedef N_CDECL_PTR(NU8*, tyProc__6AZK0DXmSc6a9a6aJ5bCqCA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(NI8*, tyProc__dL9ab7aWwUkFbidbqfV9a8oQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(NU16*, tyProc__muIl49acnjhWotJYPVeajBA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(NI16*, tyProc__t9c58USizsceKYYN9cO19aORw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(NI32*, tyProc__N5uQXLwNzYZv0y9cCIsHvcg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(NI64*, tyProc__WnF06Ir10800f9bxOz5uTVQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(float*, tyProc__Ov0X6R9aSYBhvAJiIEAlmYw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(double*, tyProc__nipykFtMX6M7VC6f10bWLg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(void, tyProc__Rc7WhipCy9bTbQ9b0P4xrsQQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__XAU2DcLhAdzy1nv9aEtYbjg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI8* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__fGkrcHllXLCQwEnpxWJc6Q) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU16* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__K6Q5gY6pKEH3k2OOBTNMOA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI16* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__ZPNdW9cm1j6gYjUhsy4XMtg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__swiEo248tCfGC9cjBzXJTOQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI64* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__Oq1Qc0MmFs01vKW8oSZGuA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, float* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__3Y6vKqGigskFWx8HPYTqdw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, double* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__LAwGUztb9cO9bLBGW8IQ3SNw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, NU8* buf);
typedef N_CDECL_PTR(void, tyProc__mKDpbYI29c4WlqDB2MdxfgA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, NI8* buf);
typedef N_CDECL_PTR(void, tyProc__t1uYrmm7ze9cOkI3CNg9aoDQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, NU16* buf);
typedef N_CDECL_PTR(void, tyProc__DanC5uiFNG2p5fR3wnhsyA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, NI16* buf);
typedef N_CDECL_PTR(void, tyProc__T9bQaVL9a5mecGvUVwXjAObw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, NI32* buf);
typedef N_CDECL_PTR(void, tyProc__A9cYEuxDSXEcNEfOS9b4LS6g) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, NI64* buf);
typedef N_CDECL_PTR(void, tyProc__JISGFcDrPe4ukzFx9c4Gtng) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, float* buf);
typedef N_CDECL_PTR(void, tyProc__nFUlZugM0AyoFrZB9cTA0Nw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, double* buf);
typedef N_CDECL_PTR(NI32, tyProc__Ls3JlIybdI7WyQv0h7aQvw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, tyObject_JNINativeMethod__L6bdxAULUoPq6MmpjHdhEA* methods, NI32 nMethods);
typedef N_CDECL_PTR(NI32, tyProc__jLkNGckLHn9cVptBOZfAooQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz);
typedef N_CDECL_PTR(NI32, tyProc__TVg9bE3u0Q9bJvGDsUMAe9bdA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj);
typedef N_CDECL_PTR(NI32, tyProc__BkSqxUGbz4le9ccVmFiLqWA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q*** vm);
typedef N_CDECL_PTR(void, tyProc__q9aElMX0QvXBI7QtBr9coUoQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* str, NI32 start, NI32 len, NU16* buf);
typedef N_CDECL_PTR(void, tyProc__EmZoaX8j4dmVScEE47WYqg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* str, NI32 start, NI32 len, NIM_CHAR* buf);
typedef N_CDECL_PTR(void*, tyProc__vARGZmgA0gPac9cjtZwcS8A) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jarraycolonObjectType___RmEW8whL9cBQ8DcJ70FJ6lg* arr, NU8* isCopy);
typedef N_CDECL_PTR(void, tyProc__nkgRR9ayIkfccFJ9b7F86TTg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jarraycolonObjectType___RmEW8whL9cBQ8DcJ70FJ6lg* arr, tyObject_jarraycolonObjectType___RmEW8whL9cBQ8DcJ70FJ6lg* carray, NI32 mode);
typedef N_CDECL_PTR(NU8, tyProc__jZGmvr5k2SkIymvdy9cc3KQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__vdZhynSxWJ2SLRDYgWv2mQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, void* address, NI64 capacity);
typedef N_CDECL_PTR(NI64, tyProc__iU8C9aHVwh1t8Vkm9cg0i9aCA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* buf);
typedef NI32 tyEnum_jobjectRefType__NS9asIjsWk4WC15RJ9cLEqRw;
typedef N_CDECL_PTR(tyEnum_jobjectRefType__NS9asIjsWk4WC15RJ9cLEqRw, tyProc__eaBBlBfAFM9bdMBYgLPqUNg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj);
struct tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw {
void* reserved0;
void* reserved1;
void* reserved2;
void* reserved3;
tyProc__GTiyzoLqRtZelJ9cswu7Uow GetVersion;
tyProc__DFZxGxC0ZHf9bsKfZXJiERg DefineClass;
tyProc__em7j1GBs7VNAXMH7F9bsLzA FindClass;
tyProc__RI5QcbnF5rKJCpfe5tSkuw FromReflectedMethod;
tyProc__RI5QcbnF5rKJCpfe5tSkuw FromReflectedField;
tyProc__6GaozS8Gb3Dr0wKgiJkjkQ ToReflectedMethod;
tyProc__VWJPYSlzvPXlCZ6l3afNaA GetSuperclass;
tyProc__4CPVQiZTL1EgQ5WgxnZgfQ IsAssignableFrom;
tyProc__6GaozS8Gb3Dr0wKgiJkjkQ ToReflectedField;
tyProc__iJRdrCdAU19cu9cNbozr6Lww Throw;
tyProc__8haEwIKzLtY9ahp2OaQCKPA ThrowNew;
tyProc__PA9cdiVOg516By6pGvaQWxw ExceptionOccurred;
tyProc__TFdHnXCI9aRT5twkNf9boeCQ ExceptionDescribe;
tyProc__TFdHnXCI9aRT5twkNf9boeCQ ExceptionClear;
tyProc__zprQk8MzhuZuCVVfs7nzAQ FatalError;
tyProc__bHzJcWtjDNDl5kZqzPrAZA PushLocalFrame;
tyProc__9aa48FNC3q6O6o7JxBTqyIg PopLocalFrame;
tyProc__9aa48FNC3q6O6o7JxBTqyIg NewGlobalRef;
tyProc__g66UlTcFcTsHnYKbhCcgkQ DeleteGlobalRef;
tyProc__g66UlTcFcTsHnYKbhCcgkQ DeleteLocalRef;
tyProc__bOP4TXpDkCCdPUdwBShcHg IsSameObject;
tyProc__9aa48FNC3q6O6o7JxBTqyIg NewLocalRef;
tyProc__bHzJcWtjDNDl5kZqzPrAZA EnsureLocalCapacity;
tyProc__JzQGCKUL8PcNxxx7x5sbnQ AllocObject;
tyProc__xDGZyxEkNgFs49a0XpRnqkw NewObject;
void* NewObjectV;
tyProc__etz1nMATyY52waZ3IHPvNA NewObjectA;
tyProc__7siyna4EZ2o31AWmBTAyeQ GetObjectClass;
tyProc__Gpd9aw5aWm5w1vetb49cc9cbA IsInstanceOf;
tyProc__SJltzEg0qYejYe9c9cKJtVhg GetMethodID;
tyProc__URa83EjSMygGDUgxAj7NJA CallObjectMethod;
void* CallObjectMethodV;
tyProc__73B0l7AF0UoF9c4pPSoPTtQ CallObjectMethodA;
tyProc__BzA25CAZLkmSibqrGJQJRw CallBooleanMethod;
void* CallBooleanMethodV;
tyProc__h0HQthcF0bCGXZqy9cjpTqw CallBooleanMethodA;
tyProc__dg2OkZ2plylt11Mvu1y1rg CallByteMethod;
void* CallByteMethodV;
tyProc__t9b0wgXJxuXOxUZ7eVy24Lw CallByteMethodA;
tyProc__sukDG9ctV6DmP4uGvm9bg73Q CallCharMethod;
void* CallCharMethodV;
tyProc__WTPd4nGpA9bMpOX9cuVNdWng CallCharMethodA;
tyProc__ysjVE7f0HAax7bq4l7H2sw CallShortMethod;
void* CallShortMethodV;
tyProc__8ZgUh9bmR8aEVUx9bRfh4E4g CallShortMethodA;
tyProc__RebaplENYTeDvBpbs8enhQ CallIntMethod;
void* CallIntMethodV;
tyProc__xkCZtbggsh19c9cU9c4avy0bQ CallIntMethodA;
tyProc__7g2iT9ct0rSELGwHNk0j9bmQ CallLongMethod;
void* CallLongMethodV;
tyProc__Dm9aqf3hllLiPUfPaYQrmyg CallLongMethodA;
tyProc__y9bhXimZiIQn0z6jBF5f9a9aQ CallFloatMethod;
void* CallFloatMethodV;
tyProc__Ft9aYwW7WlkAUG1lYfYiwsg CallFloatMethodA;
tyProc__xUnV47uHdxyCxToMt3Q8Tw CallDoubleMethod;
void* CallDoubleMethodV;
tyProc__H7q29cexnsDarOisryxp6EA CallDoubleMethodA;
tyProc__GhcJ30BBWy7mGl1OYwk1TQ CallVoidMethod;
void* CallVoidMethodV;
tyProc__IoTRuk1FmbmpFwkYmwOOLg CallVoidMethodA;
tyProc__7Nyg9b26IwfN3eF9asvxJyjQ CallNonvirtualObjectMethod;
void* CallNonvirtualObjectMethodV;
tyProc__19aFJrxpFMbyj7qtk9bz4aug CallNonvirtualObjectMethodA;
tyProc__J9bY9cgAnW8ccgmsFx3gMZug CallNonvirtualBooleanMethod;
void* CallNonvirtualBooleanMethodV;
tyProc__OFtxxZM5F3VNTX54GJ6i4A CallNonvirtualBooleanMethodA;
tyProc__y3Vi5W4aX0z9aZ4iDZX79cWA CallNonvirtualByteMethod;
void* CallNonvirtualByteMethodV;
tyProc__TYQ6u1SyWHsM16Sf58qYjQ CallNonvirtualByteMethodA;
tyProc__OpBC6GpFv76W9a13eeRvAxg CallNonvirtualCharMethod;
void* CallNonvirtualCharMethodV;
tyProc__tDXD2y1NzOhFLd2AtDZ5fw CallNonvirtualCharMethodA;
tyProc__2sD9a8bY2lRkreVu9ch5NsbQ CallNonvirtualShortMethod;
void* CallNonvirtualShortMethodV;
tyProc__kLRxt2NWwWNJtDOvfW7C8A CallNonvirtualShortMethodA;
tyProc__lvrbik67MMqeZyfUKBbAUw CallNonvirtualIntMethod;
void* CallNonvirtualIntMethodV;
tyProc__h9b5XpAcA9c8vchySeXxzz9cw CallNonvirtualIntMethodA;
tyProc__f38f9bsO9cRyGpsCgHR1FCZA CallNonvirtualLongMethod;
void* CallNonvirtualLongMethodV;
tyProc__aYl9aBKJep8aKhMwfadpAHw CallNonvirtualLongMethodA;
tyProc__CwkFdXNtFQmKc2KXYt2ung CallNonvirtualFloatMethod;
void* CallNonvirtualFloatMethodV;
tyProc__1VXPEsYRNNVX5lYxCNRYMw CallNonvirtualFloatMethodA;
tyProc__r5RRdhUbOSZE9cwdT8oa2gg CallNonvirtualDoubleMethod;
void* CallNonvirtualDoubleMethodV;
tyProc__CbVHy2WREs7HuHbKZLp3jA CallNonvirtualDoubleMethodA;
tyProc__Os2Eb35jwxBI2IIaWEc0iw CallNonvirtualVoidMethod;
void* CallNonvirtualVoidMethodV;
tyProc__kEP8rOSas4sqUu8zf8xYcA CallNonvirtualVoidMethodA;
tyProc__SJltzEg0qYejYe9c9cKJtVhg GetFieldID;
tyProc__HKl3wK9aCr9cr0LME4r9cmLIw GetObjectField;
tyProc__woDGiIz55pLskIEHDrGMdQ GetBooleanField;
tyProc__8rYdJg9cJMxMAQ4MSkIFt1Q GetByteField;
tyProc__QwHLU6Lv1w3ycvSPx9c745w GetCharField;
tyProc__jUbiAb82AubqZuyUK5NuZw GetShortField;
tyProc__D6FiM33IqK32mlI9aNPEkJg GetIntField;
tyProc__gD9cnKXpTgMQH8d5PNQD9cPw GetLongField;
tyProc__SDgCYc9b09axbMEG9baj2AwXg GetFloatField;
tyProc__yFoPhk0ty5WF3PixBEnhlg GetDoubleField;
tyProc__Q79bW7rqWtOdXHvbC0xgwpw SetObjectField;
tyProc__1MtrO0a1W77R9aGli57hiXA SetBooleanField;
tyProc__KQ6ildJWMBeSuuUfBSLrWA SetByteField;
tyProc__CMmqxHzWH24SCa9brIS5eRw SetCharField;
tyProc__rL3xq0MYJhI9cYsnvEKDr5w SetShortField;
tyProc__GQnO7229cfacsjZumf0Q9clw SetIntField;
tyProc__17Efc9ajSb8uo1XtdJADKBA SetLongField;
tyProc__PcK9a3D3iUIwc9bEYJ8ZuIsw SetFloatField;
tyProc__lqb0t9cEiwEAHi8L38RRSeg SetDoubleField;
tyProc__SJltzEg0qYejYe9c9cKJtVhg GetStaticMethodID;
tyProc__xDGZyxEkNgFs49a0XpRnqkw CallStaticObjectMethod;
void* CallStaticObjectMethodV;
tyProc__etz1nMATyY52waZ3IHPvNA CallStaticObjectMethodA;
tyProc__oD1wB8LRTaHI59b6cGvpO0w CallStaticBooleanMethod;
void* CallStaticBooleanMethodV;
tyProc__X8lAGCfdjCkE2G4IRgr9c4Q CallStaticBooleanMethodA;
tyProc__aShA4zRKZgt4bb2XM4Qcsg CallStaticByteMethod;
void* CallStaticByteMethodV;
tyProc__HwTntITjqWFDX7udUDz03w CallStaticByteMethodA;
tyProc__iKhWl09a2L9axud17FyRc79ag CallStaticCharMethod;
void* CallStaticCharMethodV;
tyProc__OEUP0541MEkD08qEqW3tBw CallStaticCharMethodA;
tyProc__hYNeRrdEzkJngiBnJEiWKQ CallStaticShortMethod;
void* CallStaticShortMethodV;
tyProc__eimIiGQ89bNtCAVEcDJsvjw CallStaticShortMethodA;
tyProc__ZgsI9cTHCZU9b9cuyfkloXi7w CallStaticIntMethod;
void* CallStaticIntMethodV;
tyProc__pYQBnp2d7pPp7xQK9bsvhzw CallStaticIntMethodA;
tyProc__kciRoaFdhzsFCxtNOZGWQA CallStaticLongMethod;
void* CallStaticLongMethodV;
tyProc__qO1ANjb6RyH1C7D0AR9avVg CallStaticLongMethodA;
tyProc__S4qMlh9bL1ZpfswLRA9cplMQ CallStaticFloatMethod;
void* CallStaticFloatMethodV;
tyProc__MP9cpv9bGHOwYgo2sxF8B9a1w CallStaticFloatMethodA;
tyProc__AOdcvx2hpu8FHwMz7ncFZw CallStaticDoubleMethod;
void* CallStaticDoubleMethodV;
tyProc__IiickGRlm8vONDL50qqdTw CallStaticDoubleMethodA;
tyProc__cWBN380E5Fl8ojwbB9bc9a3w CallStaticVoidMethod;
void* CallStaticVoidMethodV;
tyProc__sHkF9c3NXDPxCbGYf8WGRGQ CallStaticVoidMethodA;
tyProc__SJltzEg0qYejYe9c9cKJtVhg GetStaticFieldID;
tyProc__YBy37W0c9ci9b5Q2DOLx2eaw GetStaticObjectField;
tyProc__heJ5040WdyFhZw0AEVJUOA GetStaticBooleanField;
tyProc__Qqu9brExW2XMBElI7GiBgEg GetStaticByteField;
tyProc__cTBAW5ffLFlwmGSnN2Z7jw GetStaticCharField;
tyProc__C7mA6ssTTci9bUPqBlcY2OA GetStaticShortField;
tyProc__QiJvubdgP9aIlNSZJp0UsDg GetStaticIntField;
tyProc__9a4HemB9a9anUp8UmyV2ji6Pg GetStaticLongField;
tyProc__AN6iNgJutnYqiOS9cfp7Awg GetStaticFloatField;
tyProc__28AXZfa9aHIhOKZLaIjLO2Q GetStaticDoubleField;
tyProc__mCGxu1EweGI7DCYm8BC0yg SetStaticObjectField;
tyProc__gD0bgFryRPOZmXVW8x0dTQ SetStaticBooleanField;
tyProc__XeiX37CjfbMPKhLpVU9cbug SetStaticByteField;
tyProc__imFN1Tums7HoxjCtoL9aSXQ SetStaticCharField;
tyProc__CNIFxPt7Kaqp7jkAbnKFWg SetStaticShortField;
tyProc__A1nREStm4FfgwYnHXlEukw SetStaticIntField;
tyProc__AVao9bU8Z9az6o2gWKy9bSJaA SetStaticLongField;
tyProc__h7OHQ8v9cA7PA5IGNw0R8XQ SetStaticFloatField;
tyProc__M2LrteZhe9cHbQ7aIEP67Dw SetStaticDoubleField;
tyProc__6A9ckVwXiYF9cc7a6aMcJdsQ NewString;
tyProc__LF8gX9cmMvFUtPIHtUMTa8w GetStringLength;
tyProc__QgPmBpFgYnNO1DMkZ9bkAGg GetStringChars;
tyProc__5XgIEXPkM8d1N9cw3x3iMtA ReleaseStringChars;
tyProc__Et9cjhyiZpwit9acXjrn1mUQ NewStringUTF;
tyProc__LF8gX9cmMvFUtPIHtUMTa8w GetStringUTFLength;
tyProc__MCpPI6cWjZouNCHV3dU7CQ GetStringUTFChars;
tyProc__kpocOvZt9a7ioin7z16OCHQ ReleaseStringUTFChars;
tyProc__RgdS2hOQ69cMIL8hjRKXu6w GetArrayLength;
tyProc__nJ4j9cjdJLDxpitP7l9aqHFg NewObjectArray;
tyProc__pGxS2vufrSWYIHJmMGj3fQ GetObjectArrayElement;
tyProc__JQcWEFa1IdR1ickYsVcIiw SetObjectArrayElement;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewBooleanArray;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewByteArray;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewCharArray;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewShortArray;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewIntArray;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewLongArray;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewFloatArray;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewDoubleArray;
tyProc__6AZK0DXmSc6a9a6aJ5bCqCA GetBooleanArrayElements;
tyProc__dL9ab7aWwUkFbidbqfV9a8oQ GetByteArrayElements;
tyProc__muIl49acnjhWotJYPVeajBA GetCharArrayElements;
tyProc__t9c58USizsceKYYN9cO19aORw GetShortArrayElements;
tyProc__N5uQXLwNzYZv0y9cCIsHvcg GetIntArrayElements;
tyProc__WnF06Ir10800f9bxOz5uTVQ GetLongArrayElements;
tyProc__Ov0X6R9aSYBhvAJiIEAlmYw GetFloatArrayElements;
tyProc__nipykFtMX6M7VC6f10bWLg GetDoubleArrayElements;
tyProc__Rc7WhipCy9bTbQ9b0P4xrsQQ ReleaseBooleanArrayElements;
tyProc__XAU2DcLhAdzy1nv9aEtYbjg ReleaseByteArrayElements;
tyProc__fGkrcHllXLCQwEnpxWJc6Q ReleaseCharArrayElements;
tyProc__K6Q5gY6pKEH3k2OOBTNMOA ReleaseShortArrayElements;
tyProc__ZPNdW9cm1j6gYjUhsy4XMtg ReleaseIntArrayElements;
tyProc__swiEo248tCfGC9cjBzXJTOQ ReleaseLongArrayElements;
tyProc__Oq1Qc0MmFs01vKW8oSZGuA ReleaseFloatArrayElements;
tyProc__3Y6vKqGigskFWx8HPYTqdw ReleaseDoubleArrayElements;
tyProc__LAwGUztb9cO9bLBGW8IQ3SNw GetBooleanArrayRegion;
tyProc__mKDpbYI29c4WlqDB2MdxfgA GetByteArrayRegion;
tyProc__t1uYrmm7ze9cOkI3CNg9aoDQ GetCharArrayRegion;
tyProc__DanC5uiFNG2p5fR3wnhsyA GetShortArrayRegion;
tyProc__T9bQaVL9a5mecGvUVwXjAObw GetIntArrayRegion;
tyProc__A9cYEuxDSXEcNEfOS9b4LS6g GetLongArrayRegion;
tyProc__JISGFcDrPe4ukzFx9c4Gtng GetFloatArrayRegion;
tyProc__nFUlZugM0AyoFrZB9cTA0Nw GetDoubleArrayRegion;
tyProc__LAwGUztb9cO9bLBGW8IQ3SNw SetBooleanArrayRegion;
tyProc__mKDpbYI29c4WlqDB2MdxfgA SetByteArrayRegion;
tyProc__t1uYrmm7ze9cOkI3CNg9aoDQ SetCharArrayRegion;
tyProc__DanC5uiFNG2p5fR3wnhsyA SetShortArrayRegion;
tyProc__T9bQaVL9a5mecGvUVwXjAObw SetIntArrayRegion;
tyProc__A9cYEuxDSXEcNEfOS9b4LS6g SetLongArrayRegion;
tyProc__JISGFcDrPe4ukzFx9c4Gtng SetFloatArrayRegion;
tyProc__nFUlZugM0AyoFrZB9cTA0Nw SetDoubleArrayRegion;
tyProc__Ls3JlIybdI7WyQv0h7aQvw RegisterNatives;
tyProc__jLkNGckLHn9cVptBOZfAooQ UnregisterNatives;
tyProc__TVg9bE3u0Q9bJvGDsUMAe9bdA MonitorEnter;
tyProc__TVg9bE3u0Q9bJvGDsUMAe9bdA MonitorExit;
tyProc__BkSqxUGbz4le9ccVmFiLqWA GetJavaVM;
tyProc__q9aElMX0QvXBI7QtBr9coUoQ GetStringRegion;
tyProc__EmZoaX8j4dmVScEE47WYqg GetStringUTFRegion;
tyProc__vARGZmgA0gPac9cjtZwcS8A GetPrimitiveArrayCritical;
tyProc__nkgRR9ayIkfccFJ9b7F86TTg ReleasePrimitiveArrayCritical;
tyProc__QgPmBpFgYnNO1DMkZ9bkAGg GetStringCritical;
tyProc__5XgIEXPkM8d1N9cw3x3iMtA ReleaseStringCritical;
tyProc__9aa48FNC3q6O6o7JxBTqyIg NewWeakGlobalRef;
tyProc__g66UlTcFcTsHnYKbhCcgkQ DeleteWeakGlobalRef;
tyProc__jZGmvr5k2SkIymvdy9cc3KQ ExceptionCheck;
tyProc__vdZhynSxWJ2SLRDYgWv2mQ NewDirectByteBuffer;
tyProc__RI5QcbnF5rKJCpfe5tSkuw GetDirectBufferAddress;
tyProc__iU8C9aHVwh1t8Vkm9cg0i9aCA GetDirectBufferCapacity;
tyProc__eaBBlBfAFM9bdMBYgLPqUNg GetObjectRefType;
};
N_LIB_EXPORT N_CDECL(NI32, JNI_OnLoad)(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q** vmp, void* reserved);
N_NIMCALL(void, NimMain)(void);
N_LIB_EXPORT N_CDECL(tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg*, Java_com_example_nimhellojni_HelloJni_stringFromJNI)(tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* thiz);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_osDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_osInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
STRING_LITERAL(TM__txnU3daVSTgcOXMkVdHqPQ_2, "arm64-v8a", 9);
STRING_LITERAL(TM__txnU3daVSTgcOXMkVdHqPQ_3, "Hello from Nim native JNI! compiled for ", 40);
STRING_LITERAL(TM__txnU3daVSTgcOXMkVdHqPQ_4, " .", 2);
N_LIB_EXPORT N_CDECL(NI32, JNI_OnLoad)(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q** vmp, void* reserved) {	NI32 result;
{	result = (NI32)0;
	NimMain();
	result = ((NI32) 65542);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {	{
		if (!!((src == NIM_NIL))) goto LA3_;
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == NIM_NIL);
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg*, Java_com_example_nimhellojni_HelloJni_stringFromJNI)(tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* thiz) {	tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* result;
	NimStringDesc* ABI;
	NimStringDesc* T1_;
{	result = (tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg*)0;
	ABI = copyString(((NimStringDesc*) &TM__txnU3daVSTgcOXMkVdHqPQ_2));
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString((ABI ? ABI->Sup.len : 0) + 42);
appendString(T1_, ((NimStringDesc*) &TM__txnU3daVSTgcOXMkVdHqPQ_3));
appendString(T1_, ABI);
appendString(T1_, ((NimStringDesc*) &TM__txnU3daVSTgcOXMkVdHqPQ_4));
	result = (*(*env)).NewStringUTF(env, nimToCStringConv(T1_));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, initStackBottomWith)(void* locals) {	nimGC_setStackBottom(locals);
}

void PreMainInner(void) {
	stdlib_timesInit000();
	stdlib_osInit000();
}

int cmdCount;
char** cmdLine;
char** gEnv;
void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	systemDatInit000();
	initStackBottomWith((void *)&inner);
	systemInit000();
	stdlib_timesDatInit000();
	stdlib_osDatInit000();
	(*inner)();
}

N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

