/* Generated by Nim Compiler v1.6.6 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q;
typedef struct tyObject_JavaVMInitArgs__cKymzNrkoBnuXJDMMaEfiA tyObject_JavaVMInitArgs__cKymzNrkoBnuXJDMMaEfiA;
typedef N_CDECL_PTR(NI32, tyProc__VeWZhCOugPV742UOEm7dbg) (tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q*** pvm, void** penv, void* args);
typedef N_CDECL_PTR(NI32, tyProc__I3c9az5111PCFEMM1gYcH1A) (tyObject_JavaVMInitArgs__cKymzNrkoBnuXJDMMaEfiA* vm_args);
typedef N_CDECL_PTR(NI32, tyProc__YrUoJ6tyx2AIkIhA9celD0Q) (tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q*** vmBuf, NI32 bufLen, NI32* nVMs);
N_LIB_PRIVATE tyProc__VeWZhCOugPV742UOEm7dbg JNI_CreateJavaVM__jni95wrapper_1272;
N_LIB_PRIVATE tyProc__I3c9az5111PCFEMM1gYcH1A JNI_GetDefaultJavaVMInitArgs__jni95wrapper_1275;
N_LIB_PRIVATE tyProc__YrUoJ6tyx2AIkIhA9celD0Q JNI_GetCreatedJavaVMs__jni95wrapper_1280;
